# Wazuh Indexer Service
#
# This is a placeholder. Replace with actual Wazuh Indexer Service
# from the official wazuh-kubernetes repository.
#
# The service should expose:
# - Port 9200: HTTP API
# - Port 9300: Transport protocol (internal)
#
apiVersion: v1
kind: Service
metadata:
  name: wazuh-indexer
  namespace: managed-tools
  labels:
    app: wazuh
    component: indexer
    managed-by: gitops
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 9200
    targetPort: 9200
    protocol: TCP
  - name: transport
    port: 9300
    targetPort: 9300
    protocol: TCP
  selector:
    app: wazuh
    component: indexer
