apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: grafana

resources:
  # namespace created by grafana overlay (nprd-apps has both)
  - alloy-helmchart.yaml
  - prometheus-helmchart.yaml

commonLabels:
  app: monitoring
  managed-by: gitops
