apiVersion: v1
kind: Namespace
metadata:
  name: harbor
  labels:
    name: harbor
    purpose: container-registry
    app: harbor
    managed-by: gitops
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: gitops-tools-nprd-apps-harbor-base
    meta.helm.sh/release-namespace: harbor