apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: containerd-harbor-cert-config
  namespace: managed-cicd
  labels:
    app: containerd-harbor-cert-config
    managed-by: gitops
spec:
  selector:
    matchLabels:
      app: containerd-harbor-cert-config
  template:
    metadata:
      labels:
        app: containerd-harbor-cert-config
        managed-by: gitops
    spec:
      # Run on all nodes (including master)
      tolerations:
        # Allow running on master nodes (K3s doesn't have taints by default, but this is good practice)
        - effect: NoSchedule
          operator: Exists
        - effect: NoExecute
          operator: Exists
      # Use host network to access node filesystem
      hostNetwork: true
      # Privileged container to write to node filesystem
      containers:
      - name: cert-config
        image: alpine:latest
        command:
        - /bin/sh
        - -c
        - |
          set -e
          
          HARBOR_URL="harbor.dataknife.net"
          MOUNTED_CERT="/cert/ca.crt"
          
          # K3s registry configuration paths
          K3S_REGISTRY_DIR="/etc/rancher/k3s"
          K3S_REGISTRY_YAML="${K3S_REGISTRY_DIR}/registries.yaml"
          K3S_CERT_FILE="${K3S_REGISTRY_DIR}/harbor-ca.crt"
          
          # Also configure containerd certs.d directory (backup method)
          CONTAINERD_CERTS_DIR="/var/lib/rancher/k3s/agent/etc/containerd/certs.d/${HARBOR_URL}"
          CONTAINERD_CERT_FILE="${CONTAINERD_CERTS_DIR}/ca.crt"
          
          echo "Configuring K3s to trust Harbor registry certificate..."
          echo "K3s registry config: ${K3S_REGISTRY_YAML}"
          echo "K3s certificate file: ${K3S_CERT_FILE}"
          echo "Mounted certificate: ${MOUNTED_CERT}"
          
          # Check if mounted certificate exists
          if [ ! -f "${MOUNTED_CERT}" ]; then
            echo "Error: Mounted certificate not found at ${MOUNTED_CERT}"
            exit 1
          fi
          
          # Create K3s registry directory
          echo "Creating K3s registry directory: ${K3S_REGISTRY_DIR}"
          mkdir -p "${K3S_REGISTRY_DIR}"
          
          # Copy certificate for K3s registries.yaml
          echo "Copying certificate to ${K3S_CERT_FILE}"
          cp "${MOUNTED_CERT}" "${K3S_CERT_FILE}"
          chmod 644 "${K3S_CERT_FILE}"
          
          # Create K3s registries.yaml configuration
          echo "Creating K3s registries.yaml configuration..."
          cat > "${K3S_REGISTRY_YAML}" <<EOF
          mirrors:
            "${HARBOR_URL}":
              endpoint:
                - "https://${HARBOR_URL}"
          configs:
            "${HARBOR_URL}":
              tls:
                ca_file: "${K3S_CERT_FILE}"
          EOF
          
          chmod 644 "${K3S_REGISTRY_YAML}"
          echo "✓ K3s registries.yaml created"
          
          # Also configure containerd certs.d (for compatibility)
          echo "Also configuring containerd certs.d directory..."
          mkdir -p "${CONTAINERD_CERTS_DIR}"
          cp "${MOUNTED_CERT}" "${CONTAINERD_CERT_FILE}"
          chmod 644 "${CONTAINERD_CERT_FILE}"
          echo "✓ containerd certs.d configured"
          
          echo "✓ Certificate configuration complete"
          echo "K3s registries.yaml: ${K3S_REGISTRY_YAML}"
          echo "Certificate file: ${K3S_CERT_FILE}"
          echo ""
          echo "Note: K3s service may need to be restarted for changes to take effect."
          echo "The certificate is configured, but you may need to run:"
          echo "  sudo systemctl restart k3s-agent  # or k3s on master nodes"
          echo ""
          echo "Keeping container running to maintain configuration..."
          while true; do
            # Verify certificate and config files still exist every 60 seconds
            if [ ! -f "${K3S_CERT_FILE}" ] || [ ! -f "${K3S_REGISTRY_YAML}" ]; then
              echo "Warning: Certificate or config missing, re-applying..."
              mkdir -p "${K3S_REGISTRY_DIR}"
              cp "${MOUNTED_CERT}" "${K3S_CERT_FILE}"
              chmod 644 "${K3S_CERT_FILE}"
              cat > "${K3S_REGISTRY_YAML}" <<EOF
          mirrors:
            "${HARBOR_URL}":
              endpoint:
                - "https://${HARBOR_URL}"
          configs:
            "${HARBOR_URL}":
              tls:
                ca_file: "${K3S_CERT_FILE}"
          EOF
              chmod 644 "${K3S_REGISTRY_YAML}"
            fi
            sleep 60
          done
        securityContext:
          privileged: true
        volumeMounts:
        - name: harbor-cert
          mountPath: /cert
          readOnly: true
        - name: k3s-containerd-certs
          mountPath: /var/lib/rancher/k3s/agent/etc/containerd/certs.d
        - name: k3s-registry-config
          mountPath: /etc/rancher/k3s
      volumes:
      - name: harbor-cert
        secret:
          secretName: harbor-ca-cert
          items:
          - key: ca.crt
            path: ca.crt
      - name: k3s-containerd-certs
        hostPath:
          path: /var/lib/rancher/k3s/agent/etc/containerd/certs.d
          type: DirectoryOrCreate
      - name: k3s-registry-config
        hostPath:
          path: /etc/rancher/k3s
          type: DirectoryOrCreate
      restartPolicy: Always
