# Wazuh Indexer Security Initialization Job
# This Job runs securityadmin.sh to properly initialize/update security configuration
# Run this AFTER the indexer is ready to apply security settings from ConfigMap
apiVersion: batch/v1
kind: Job
metadata:
  name: wazuh-indexer-security-init
  namespace: managed-tools
  labels:
    app: wazuh
    component: indexer
    managed-by: gitops
    job-type: security-init
  annotations:
    # This job should only run once - delete it manually after successful completion
    # or use TTL after finished controller if available
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  # Only run once - if it already exists, don't recreate
  backoffLimit: 3
  ttlSecondsAfterFinished: 86400  # Delete job 24 hours after completion
  template:
    metadata:
      labels:
        app: wazuh
        component: indexer
        managed-by: gitops
        job-type: security-init
    spec:
      restartPolicy: OnFailure
      serviceAccountName: default
      containers:
      - name: securityadmin
        image: wazuh/wazuh-indexer:4.14.1
        command:
          - /bin/bash
          - -c
          - |
            set -e
            echo "Waiting for Wazuh Indexer to be ready..."
            # Wait for indexer to be healthy
            until curl -k -s https://wazuh-indexer:9200/_cluster/health | grep -q '"status":"green"\|"status":"yellow"'; do
              echo "Waiting for indexer to be ready..."
              sleep 10
            done
            echo "Indexer is ready, waiting additional 30 seconds for full initialization..."
            sleep 30
            
            export INSTALLATION_DIR=/usr/share/wazuh-indexer
            export OPENSEARCH_PATH_CONF=${INSTALLATION_DIR}/config
            export CACERT=$OPENSEARCH_PATH_CONF/certs/root-ca.pem
            export KEY=$OPENSEARCH_PATH_CONF/certs/admin-key.pem
            export CERT=$OPENSEARCH_PATH_CONF/certs/admin.pem
            export JAVA_HOME=/usr/share/wazuh-indexer/jdk
            
            echo "Applying security configuration from ConfigMap..."
            bash /usr/share/wazuh-indexer/plugins/opensearch-security/tools/securityadmin.sh \
              -cd /usr/share/wazuh-indexer/config/opensearch-security \
              -nhnv \
              -cacert $CACERT \
              -cert $CERT \
              -key $KEY \
              -p 9200 \
              -icl \
              -h wazuh-indexer
              
            echo "Security configuration applied successfully!"
        env:
        - name: JAVA_HOME
          value: /usr/share/wazuh-indexer/jdk
        volumeMounts:
        - name: indexer-certs
          mountPath: /usr/share/wazuh-indexer/config/certs
          readOnly: true
        - name: indexer-conf
          mountPath: /usr/share/wazuh-indexer/config/opensearch-security
          readOnly: true
      volumes:
      - name: indexer-certs
        secret:
          secretName: wazuh-certs
          defaultMode: 0600
      - name: indexer-conf
        configMap:
          name: wazuh-indexer-config
          defaultMode: 0600
          items:
          - key: internal_users.yml
            path: internal_users.yml
