apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: game-servers
resources:
  - envoyproxy-satisfactory.yaml
  - envoyproxy-windrose.yaml
  - clusterip-services.yaml
  - satisfactory-gateway.yaml
  - satisfactory-routes.yaml
  - windrose-gateway.yaml
  - windrose-routes.yaml
