# Example HorizontalRunnerAutoscaler for GitHub Actions Runner Controller
# This enables autoscaling of runners based on workflow demand
#
# Apply this after the RunnerDeployment is created:
#   kubectl apply -f horizontalrunnerautoscaler-example.yaml

apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: github-runner-autoscaler
  namespace: managed-cicd
spec:
  scaleTargetRef:
    name: github-runner-deployment
  minReplicas: 1
  maxReplicas: 10
  metrics:
    # Scale based on percentage of runners in use
    - type: PercentageRunnersBusy
      scaleUpThreshold: "0.75"    # Scale up when 75% of runners are busy
      scaleDownThreshold: "0.25"  # Scale down when less than 25% are busy
      scaleUpAdjustment: 2       # Add 2 runners when scaling up
      scaleDownAdjustment: 1      # Remove 1 runner when scaling down
  
  # Alternative: Scale based on total number of queued workflows
  # metrics:
  #   - type: TotalNumberOfQueuedAndInProgressWorkflowRuns
  #     repositoryNames:
  #       - <YOUR_GITHUB_ORG>/<YOUR_REPO>
  
  # Alternative: Scale based on queued workflows per repository
  # metrics:
  #   - type: NumberOfQueuedAndInProgressWorkflowRuns
  #     repositoryNames:
  #       - <YOUR_GITHUB_ORG>/<YOUR_REPO>
  
  # Scale down delay (optional)
  scaleDownDelaySecondsAfterScaleOut: 300  # Wait 5 minutes before scaling down
